site_name: AI X Lab Technical Documentation
nav:
  - Home: index.md
  - Infrastructure: infra.md
  - Procedures and Instructions: howto.md
  - Useful Software: software.md
  - Editing the docs: editdocs.md
  - About: about.md

site_url: https://aixlab-d3-nsbe-nms.github.io/
repo_url: https://github.com/aixlab-d3-nsbe-nms/aixlab-d3-nsbe-nms.github.io
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.expand       # sidebar items expanded
    - navigation.top          # back-to-top button
    - search.highlight
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal        # or: white, grey, blue grey, teal
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition              # nice note/warning callouts
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.highlight:
      anchor_linenums: false
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.mark
  - footnotes
  - def_list
  - attr_list
