site_name: AI X Lab Technical Documentation
nav:
  - Home: index.md
  - Infrastructure: infra.md
  - Procedures and Instructions: howto.md
  - Useful Software: software.md
  - Editing the docs: editdocs.md
  - About: about.md
theme: readthedocs

site_url: https://aixlab-d3-nsbe-nms.github.io/
repo_url: https://github.com/aixlab-d3-nsbe-nms/aixlab-d3-nsbe-nms.github.io
edit_uri: edit/main/docs/
